controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.30
    wheel_radius: 0.06
    cmd_vel_timeout: 0.5
    linear:
      x:
        min: -0.5
        max: 0.5
        max_accel: 2.0
    angular:
      z:
        min: -3.0
        max: 3.0
        max_accel: 5.0

